-- LendGuard: digital lending risk demonstration
-- MySQL 8.0+
-- All records generated by the companion seed script are synthetic.

CREATE DATABASE IF NOT EXISTS lendguard_demo
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE lendguard_demo;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS monthly_repayments;
DROP TABLE IF EXISTS loan_accounts;
DROP TABLE IF EXISTS bureau_enquiries;
DROP TABLE IF EXISTS bureau_tradelines;
DROP TABLE IF EXISTS loan_applications;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS lender_partners;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE lender_partners (
  partner_id SMALLINT UNSIGNED PRIMARY KEY,
  partner_name VARCHAR(80) NOT NULL,
  partner_type ENUM('BANK','NBFC','FINTECH') NOT NULL,
  risk_share_pct DECIMAL(5,2) NOT NULL,
  target_apr_pct DECIMAL(5,2) NOT NULL,
  active_flag BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT chk_partner_risk_share CHECK (risk_share_pct BETWEEN 0 AND 100),
  CONSTRAINT chk_partner_apr CHECK (target_apr_pct BETWEEN 0 AND 100),
  UNIQUE KEY uk_partner_name (partner_name)
) ENGINE=InnoDB;

CREATE TABLE customers (
  customer_id INT UNSIGNED PRIMARY KEY,
  synthetic_customer_ref VARCHAR(20) NOT NULL,
  age SMALLINT UNSIGNED NOT NULL,
  employment_type ENUM('SALARIED','SELF_EMPLOYED','GIG','OTHER') NOT NULL,
  monthly_income DECIMAL(12,2) NOT NULL,
  city_tier ENUM('TIER_1','TIER_2','TIER_3') NOT NULL,
  created_at DATETIME NOT NULL,
  CONSTRAINT chk_customer_age CHECK (age BETWEEN 21 AND 70),
  CONSTRAINT chk_customer_income CHECK (monthly_income > 0),
  UNIQUE KEY uk_customer_ref (synthetic_customer_ref)
) ENGINE=InnoDB;

CREATE TABLE loan_applications (
  application_id INT UNSIGNED PRIMARY KEY,
  customer_id INT UNSIGNED NOT NULL,
  partner_id SMALLINT UNSIGNED NOT NULL,
  application_date DATE NOT NULL,
  requested_amount DECIMAL(12,2) NOT NULL,
  requested_tenure_months SMALLINT UNSIGNED NOT NULL,
  product_code ENUM('PERSONAL_LOAN','LINE_OF_CREDIT','CONSUMER_LOAN') NOT NULL,
  channel_code ENUM('DIRECT','PARTNER','MARKETPLACE') NOT NULL,
  bureau_processed_at DATETIME NULL,
  decision_status ENUM('PENDING','APPROVED','REJECTED') NOT NULL,
  decision_date DATE NULL,
  rejection_reason VARCHAR(120) NULL,
  disbursal_flag BOOLEAN NOT NULL DEFAULT FALSE,
  disbursal_date DATE NULL,
  CONSTRAINT fk_application_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_application_partner FOREIGN KEY (partner_id) REFERENCES lender_partners(partner_id),
  CONSTRAINT chk_requested_amount CHECK (requested_amount > 0),
  CONSTRAINT chk_requested_tenure CHECK (requested_tenure_months BETWEEN 3 AND 60),
  CONSTRAINT chk_application_timeline CHECK (decision_date IS NULL OR decision_date >= application_date),
  INDEX ix_application_customer (customer_id),
  INDEX ix_application_partner_date (partner_id, application_date),
  INDEX ix_application_status (decision_status, disbursal_flag)
) ENGINE=InnoDB;

CREATE TABLE bureau_tradelines (
  tradeline_id BIGINT UNSIGNED PRIMARY KEY,
  customer_id INT UNSIGNED NOT NULL,
  application_id INT UNSIGNED NOT NULL,
  bureau_report_date DATE NOT NULL,
  account_type ENUM('CREDIT_CARD','PERSONAL_LOAN','AUTO_LOAN','HOME_LOAN','OTHER') NOT NULL,
  opened_date DATE NOT NULL,
  credit_limit DECIMAL(12,2) NOT NULL DEFAULT 0,
  current_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  overdue_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  maximum_dpd SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  writeoff_flag BOOLEAN NOT NULL DEFAULT FALSE,
  secured_flag BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_tradeline_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_tradeline_application FOREIGN KEY (application_id) REFERENCES loan_applications(application_id),
  CONSTRAINT chk_tradeline_values CHECK (credit_limit >= 0 AND current_balance >= 0 AND overdue_amount >= 0),
  CONSTRAINT chk_tradeline_opened_before_report CHECK (opened_date <= bureau_report_date),
  INDEX ix_tradeline_application (application_id, bureau_report_date),
  INDEX ix_tradeline_customer (customer_id)
) ENGINE=InnoDB;

CREATE TABLE bureau_enquiries (
  enquiry_id BIGINT UNSIGNED PRIMARY KEY,
  customer_id INT UNSIGNED NOT NULL,
  application_id INT UNSIGNED NOT NULL,
  bureau_report_date DATE NOT NULL,
  enquiry_date DATE NOT NULL,
  enquiry_purpose ENUM('PERSONAL_LOAN','CREDIT_CARD','AUTO_LOAN','HOME_LOAN','OTHER') NOT NULL,
  CONSTRAINT fk_enquiry_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_enquiry_application FOREIGN KEY (application_id) REFERENCES loan_applications(application_id),
  CONSTRAINT chk_enquiry_before_report CHECK (enquiry_date <= bureau_report_date),
  INDEX ix_enquiry_application_date (application_id, enquiry_date),
  INDEX ix_enquiry_customer (customer_id)
) ENGINE=InnoDB;

CREATE TABLE loan_accounts (
  account_id INT UNSIGNED PRIMARY KEY,
  synthetic_account_ref VARCHAR(20) NOT NULL,
  application_id INT UNSIGNED NOT NULL,
  customer_id INT UNSIGNED NOT NULL,
  partner_id SMALLINT UNSIGNED NOT NULL,
  disbursal_date DATE NOT NULL,
  funded_principal DECIMAL(12,2) NOT NULL,
  annual_interest_rate_pct DECIMAL(5,2) NOT NULL,
  tenure_months SMALLINT UNSIGNED NOT NULL,
  scheduled_instalment DECIMAL(12,2) NOT NULL,
  account_status ENUM('ACTIVE','CLOSED','WRITTEN_OFF') NOT NULL DEFAULT 'ACTIVE',
  CONSTRAINT fk_account_application FOREIGN KEY (application_id) REFERENCES loan_applications(application_id),
  CONSTRAINT fk_account_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
  CONSTRAINT fk_account_partner FOREIGN KEY (partner_id) REFERENCES lender_partners(partner_id),
  CONSTRAINT chk_funded_principal CHECK (funded_principal > 0),
  CONSTRAINT chk_account_apr CHECK (annual_interest_rate_pct BETWEEN 0 AND 100),
  CONSTRAINT chk_account_tenure CHECK (tenure_months BETWEEN 3 AND 60),
  UNIQUE KEY uk_account_ref (synthetic_account_ref),
  UNIQUE KEY uk_account_application (application_id),
  INDEX ix_account_partner_disbursal (partner_id, disbursal_date),
  INDEX ix_account_customer (customer_id)
) ENGINE=InnoDB;

CREATE TABLE monthly_repayments (
  repayment_id BIGINT UNSIGNED PRIMARY KEY,
  account_id INT UNSIGNED NOT NULL,
  instalment_number SMALLINT UNSIGNED NOT NULL,
  due_date DATE NOT NULL,
  scheduled_amount DECIMAL(12,2) NOT NULL,
  paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  last_payment_date DATE NULL,
  days_past_due SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  outstanding_principal DECIMAL(12,2) NOT NULL,
  repayment_status ENUM('NOT_DUE','PAID','PARTIAL','MISSED') NOT NULL,
  reporting_month_end DATE NOT NULL,
  CONSTRAINT fk_repayment_account FOREIGN KEY (account_id) REFERENCES loan_accounts(account_id),
  CONSTRAINT chk_repayment_amounts CHECK (scheduled_amount >= 0 AND paid_amount >= 0 AND outstanding_principal >= 0),
  CONSTRAINT chk_instalment_number CHECK (instalment_number > 0),
  UNIQUE KEY uk_account_instalment_snapshot (account_id, instalment_number, reporting_month_end),
  INDEX ix_repayment_reporting (reporting_month_end, days_past_due),
  INDEX ix_repayment_account_due (account_id, due_date)
) ENGINE=InnoDB;
